### ISSUE TITLE
Are Recurring Payments Supported?

### ISSUE THREAD

**Issue by MartinMekhaiel** [terdelyi/omnipay-wirecard#3]
We are implementing this module and we need recurring payments, as we are in the travel industry we have to take 10% deposit upfront and 20 days before departure of the guest we need to withdraw the open 90% from the client. Wirecard does support this feature in an extra option . Thank you for your response! regards

**Comment by terdelyi** [comment]
Hello @djtak47!

As you can read on [Omnipay's website](https://omnipay.thephpleague.com/api/recurring-billing/) "automatic recurring payments functionality is out of scope for this library", what I can also say about my package as it's based on Omnipay's workflow.

However recurring payments are [supported as an option by Checkout Page](https://guides.wirecard.at/request_parameters#transactionidentifier), but if I'm reading right only for **PayPal** and **SEPA Direct Debit** payments. It will use details of the first transaction, but you also need to setup a [recurPayment](https://guides.wirecard.at/back-end_operations:transaction-based:recurpayment) on your side what will handle the recurring backend operation.

Anyway it might sounds astounding, but I suggest you to _avoid using Omnipay_, because the development of the package has been on hold for a while and I'm not very optimistic about its future. If modular gateways are not important for you I recommend you Wirecard's own pure PHP codes:

https://github.com/wirecard/wcp-example-php
https://github.com/wirecard/wcp-back-end-example-php
